//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHorizontalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IstorijaVlasnika
    {
        public int VlasnikID { get; set; }
        public Nullable<int> VoziloID { get; set; }
        public string TipVlasnika { get; set; }
        public string ZemljaRegistracije { get; set; }
        public Nullable<System.DateTime> DatumOd { get; set; }
        public Nullable<System.DateTime> DatumDo { get; set; }
    
        public virtual Vozila Vozila { get; set; }
    }
}
