//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHorizontalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KupljeniIzvjestaji
    {
        public int IzvjestajID { get; set; }
        public Nullable<int> KorisnikID { get; set; }
        public Nullable<int> VoziloID { get; set; }
        public Nullable<System.DateTime> DatumKupovine { get; set; }
        public decimal Cijena { get; set; }
        public string StatusPlacanja { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Vozila Vozila { get; set; }
    }
}
