//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHorizontalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogoviAktivnosti
    {
        public int LogID { get; set; }
        public Nullable<int> KorisnikID { get; set; }
        public string Akcija { get; set; }
        public string OpisAktivnosti { get; set; }
        public Nullable<System.DateTime> DatumVrijeme { get; set; }
    }
}
