//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHorizontalWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CarHorizontalBaza : DbContext
    {
        public CarHorizontalBaza()
            : base("name=CarHorizontalBaza")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IstorijaVlasnika> IstorijaVlasnikas { get; set; }
        public virtual DbSet<Korisnici> Korisnicis { get; set; }
        public virtual DbSet<KupljeniIzvjestaji> KupljeniIzvjestajis { get; set; }
        public virtual DbSet<LogoviAktivnosti> LogoviAktivnostis { get; set; }
        public virtual DbSet<ProfiliKorisnika> ProfiliKorisnikas { get; set; }
        public virtual DbSet<ServisnaIstorija> ServisnaIstorijas { get; set; }
        public virtual DbSet<StatusPotrage> StatusPotrages { get; set; }
        public virtual DbSet<Uloge> Uloges { get; set; }
        public virtual DbSet<Vozila> Vozilas { get; set; }
        public virtual DbSet<ZapisiKilometraze> ZapisiKilometrazes { get; set; }
        public virtual DbSet<ZapisiNesreca> ZapisiNesrecas { get; set; }
    
        public virtual ObjectResult<Sp_BrzaPretragaVozila_Result> Sp_BrzaPretragaVozila(string vIN)
        {
            var vINParameter = vIN != null ?
                new ObjectParameter("VIN", vIN) :
                new ObjectParameter("VIN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_BrzaPretragaVozila_Result>("Sp_BrzaPretragaVozila", vINParameter);
        }
    
        public virtual ObjectResult<Sp_DetaljnaPretragaVozila_Result> Sp_DetaljnaPretragaVozila(string marka, string model, string gorivo)
        {
            var markaParameter = marka != null ?
                new ObjectParameter("Marka", marka) :
                new ObjectParameter("Marka", typeof(string));
    
            var modelParameter = model != null ?
                new ObjectParameter("Model", model) :
                new ObjectParameter("Model", typeof(string));
    
            var gorivoParameter = gorivo != null ?
                new ObjectParameter("Gorivo", gorivo) :
                new ObjectParameter("Gorivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_DetaljnaPretragaVozila_Result>("Sp_DetaljnaPretragaVozila", markaParameter, modelParameter, gorivoParameter);
        }
    }
}
