//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHorizontalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfiliKorisnika
    {
        public int ProfilID { get; set; }
        public Nullable<int> KorisnikID { get; set; }
        public string BrojTelefona { get; set; }
        public string Grad { get; set; }
        public string Drzava { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
    }
}
