//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHorizontalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServisnaIstorija
    {
        public int ServisID { get; set; }
        public Nullable<int> VoziloID { get; set; }
        public string OpisServisa { get; set; }
        public Nullable<decimal> CijenaServisa { get; set; }
        public System.DateTime DatumServisa { get; set; }
        public string NazivServisa { get; set; }
    
        public virtual Vozila Vozila { get; set; }
    }
}
