//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHorizontalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusPotrage
    {
        public int PotragaID { get; set; }
        public Nullable<int> VoziloID { get; set; }
        public Nullable<bool> IsUkraden { get; set; }
        public string DrzavaPrijave { get; set; }
        public Nullable<System.DateTime> DatumPrijave { get; set; }
    
        public virtual Vozila Vozila { get; set; }
    }
}
