//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHorizontalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozila
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vozila()
        {
            this.IstorijaVlasnikas = new HashSet<IstorijaVlasnika>();
            this.KupljeniIzvjestajis = new HashSet<KupljeniIzvjestaji>();
            this.ServisnaIstorijas = new HashSet<ServisnaIstorija>();
            this.StatusPotrages = new HashSet<StatusPotrage>();
            this.ZapisiKilometrazes = new HashSet<ZapisiKilometraze>();
            this.ZapisiNesrecas = new HashSet<ZapisiNesreca>();
        }
    
        public int VoziloID { get; set; }
        public string VIN { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public int Godiste { get; set; }
        public Nullable<int> Kubikaza { get; set; }
        public Nullable<int> SnagaKS { get; set; }
        public string Gorivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IstorijaVlasnika> IstorijaVlasnikas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KupljeniIzvjestaji> KupljeniIzvjestajis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServisnaIstorija> ServisnaIstorijas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusPotrage> StatusPotrages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZapisiKilometraze> ZapisiKilometrazes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZapisiNesreca> ZapisiNesrecas { get; set; }
    }
}
