//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHorizontalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZapisiKilometraze
    {
        public int ZapisID { get; set; }
        public Nullable<int> VoziloID { get; set; }
        public int Kilometraza { get; set; }
        public System.DateTime DatumZapisa { get; set; }
        public string IzvorZapisa { get; set; }
    
        public virtual Vozila Vozila { get; set; }
    }
}
