//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarHorizontalWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZapisiNesreca
    {
        public int NesrecaID { get; set; }
        public Nullable<int> VoziloID { get; set; }
        public System.DateTime DatumNesrece { get; set; }
        public string OpisOstecenja { get; set; }
        public Nullable<decimal> ProcijenjenaStetaEVR { get; set; }
    
        public virtual Vozila Vozila { get; set; }
    }
}
